### ISSUE TITLE
Size of dependencies: usage for "attranslate"

### ISSUE THREAD

**Issue by fkirc** [googleapis/nodejs-translate#595] opened 2020-11-07 19:48 UTC
`nodejs-translate` has become a critical part of `attranslate`: https://github.com/fkirc/attranslate
It works great, and my only gripe is the sheer size of the non-dev dependencies.
In fact, I had to utilize a "dynamic import" for `nodejs-translate`, because otherwise the launch time of `atttanslate` would be too slow.

Therefore, it would be nice if you could find a way to reduce the size and number of the non-dev dependencies that are currently used.

**Comment by alexander-fenster** [comment] 2020-11-10 21:15
Hi @fkirc,

Thank you for your request. The longer load time of this library (compared to other Google Cloud libraries) may be caused by the fact that `v2` and `v3*` versions of the API use completely different stacks, and since the library exports all versions, it negatively affects the load time.  Look at this [trace](https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://gist.githubusercontent.com/alexander-fenster/89ba95f40b4db65b4d9350c6c0f24f16/raw/dda712097b71b5712b0e084a76ee6f68d88be457/gistfile1.txt
) produced by `require-so-slow` (this is on my laptop, definitely not the fastest computer in the universe):

![image](https://user-images.githubusercontent.com/4015807/98734409-c1c4ec80-2356-11eb-809c-ff01fef7d406.png)

We are not going to drop `v2` from this library any time soon (this will be a breaking change for existing users). One thing I can suggest for you is to use a bundler (`webpack` or anything like that) to strip the API versions you don't need: if your code only uses `v3`, block `v2` and `v3beta1` from loading.

**Comment by fkirc** [comment] 2020-11-16 08:50
Thanks for the detailed profiling.
I might try to strip out everything except of v3 and then report if I can achieve an improved launch performance. 

Beside of launch performance, the other issue is package download size.
Other than maintaining a fork, I do not see any short term solution?

For the future, I would be happy if you release a stripped down major version with only the dependencies that are really necessary, and then keep the current version on a maintenance branch to keep it available for legacy users.

**Comment by munkhuushmgl** [comment] 2021-06-21 21:21
IM closing this issue, I hope your issue has been resolved 

if not, feel free to reopen

**Closed by munkhuushmgl** 2021-06-21 21:21 UTC
Labels: api: translate, type: feature request
